### ISSUE TITLE
iTunes Receipt validation and Application receipt

### ISSUE THREAD

**Issue by geshub** [aporat/store-receipt-validator#112]
Recently the plugin I'm using on the mobile side started to send the "Application receipt" to my backend. I understand that an Application receipt is a receipt created automatically when the user download the app from the appstore. (even a free app)
My verification code is similar to the one on your example page and I noticed those "Application receipts" are validated ( $response->isValid() ).
I presume in that case we need another check after isValid() ? as any "Application receipt" is valid even without any purchase.
What is the best way to deal with this ?

**Comment by Stafox** [comment]
It depends on what you want to detect.

You can iterate all transactions and check is there any active subscription to provide premium functionality in your app.

You can check is user bought subscriptions previously to detect offer/intro price eligibility.

By the way this library detect expired receipt as invalid, so you should handle this case in your wrapper.

**Comment by geshub** [comment]
@Stafox In my case I'm only selling consumables.
Right now I started to check the purchase after $response->isValid(),
But it's important to know that you can't rely on $response->isValid() to give access to a consumable product as any "Application receipt" is valid without any purchase.

**Comment by Stafox** [comment]
Yes, validation in not responsible for granting logic.

As you work with consumables, you should know that they disappear from receipt after **finishTransaction()**.

More info here: https://developer.apple.com/documentation/storekit/in-app_purchase/choosing_a_receipt_validation_technique
