### ISSUE TITLE
The current user has insufficient permissions to perform the requested operation.

### ISSUE THREAD

**Issue by birdeveloper** [aporat/store-receipt-validator#114]
Hello, I have done the setups and steps correctly but I get this error and there is nothing clear about its solution. I am trying to verify the invoice in Google Play Billing, the result returned to me is as follows:

`got error = { "error": { "errors": [ { "domain": "androidpublisher", "reason": "permissionDenied", "message": "The current user has insufficient permissions to perform the requested operation." } ], "code": 401, "message": "The current user has insufficient permissions to perform the requested operation." } }`

**Comment by Stafox** [comment]
It means you have not provide effficient permisions while created service account.
You can follow these instructions:

https://www.revenuecat.com/blog/android-subscriptions-tutorial
**Creating service credentials**

**Comment by birdeveloper** [comment]
@Stafox I followed these instructions, but didn't there any other solution?

**Comment by Stafox** [comment]
What kind solution? Google directly said that you have no permission.

**Comment by birdeveloper** [comment]
But there is no problem in my permissions and codes, I have been dealing for 3 days why always says that, I have only one thing in mind. I wonder now, because of COVID-19, Google extended the comebacks, so is it late in confirming the powers of the Auth account?

**Comment by Stafox** [comment]
Try to repeat again the steps about creating the service account.
And make sure that this service account connected with your app.

I have no idea how to help you with that. Sorry.

**Comment by birdeveloper** [comment]
thank u sir :/

**Comment by Stafox** [comment]
@birdeveloper Did you find a way how to fix your problem?

**Comment by birdeveloper** [comment]
@Stafox O gün çalışmayı bıraktım. Ertesi gün çalışmaya başladığımda sorun kendiliğinden çözüldü. Çözümün ne olduğunu bilmiyorum

**Comment by birdeveloper** [comment]
@Stafox I stopped working that day. The problem resolved spontaneously when I started working the next day. I don't know what the solution.
