### ISSUE TITLE
Acknowledger Wrong parameters for RuntimeException

### ISSUE THREAD

**Issue by dariusvalys** [aporat/store-receipt-validator#115]
Trying to acknowledge in GooglePlay/Acknowledger.php got RuntimeException error: Wrong parameters for RuntimeException and can not use this method.

PHP 7.3.15

**Comment by Stafox** [comment]
@dariusvalys thanks. Will fix it right now. Looks like argument `$code` was missing

**Comment by Stafox** [comment]
@dariusvalys fixed in https://github.com/aporat/store-receipt-validator/releases/tag/3.4.1

**Comment by dariusvalys** [comment]
working good. thanks
