### ISSUE TITLE
Google forbidden request

### ISSUE THREAD

**Issue by blood73** [aporat/store-receipt-validator#118]
I checked subscription for Google Play very often, I think. Google banned IP. Now I received this for any request:

<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>

How I can quick fix thix problem? I need to add proxy server temporarily. Is it possible?

**Comment by Stafox** [comment]
I see the same situation. More than 150k errors since 14:00 UTC time.

Looks like there is an issue on the google side.

In my case i've used internal cache to reduce amount of requests to API as recommended by google.

I have saw something similar to this a week ago, but it was fixed in a short time.

**Comment by blood73** [comment]
> In my case i've used internal cache to reduce amount of requests to API as recommended by google.

I found a possibility to add a proxy to request to API and it works for me. Without proxy doesn't work.

File vendor/guzzlehttp/guzzle/src/Client.php
public function send(RequestInterface $request, array $options = [])

add this line:

$options[RequestOptions::PROXY] = 'proxy_string';

**Comment by Stafox** [comment]
For me it looks like API requests have been started to handle by general google firewall (which responsible for filtering google search requests).

In that case proxy will be banned soon.

**Comment by Stafox** [comment]
Looks like googleapis up
