### ISSUE TITLE
Bug on iOS cURL error 2: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by zahidurr** [aporat/store-receipt-validator#119]
Suddenly I am getting below error message when I call iOS recurring subscriptions. Before it worked well.

> cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 

`$response = $validator->setSharedSecret($sharedSecret)->setReceiptData($receiptBase64Data)->validate()`;

PHP Version 7.3.16
cURL: 7.69.1

**Comment by Stafox** [comment]
Curl errors are not a problem of that library. It’s a network problem between yours and Apple server.

How many errors you got?
How many requests were successfully done?
Do you make a retry on error?

Pleased, read the conversation in that pull request https://github.com/aporat/store-receipt-validator/pull/113

**Comment by zahidurr** [comment]
> Curl errors are not a problem of that library. It’s a network problem between yours and Apple server.

Thanks for the info

> 
> How many errors you got?

I get errors for every request from second one

> How many requests were successfully done?

Only one

> Do you make a retry on error?

No

> 
> Pleased, read the conversation in that pull request #113

Ok. But there is no details info regarding setRequestOptions() method. What type request is passable?

**Comment by Stafox** [comment]
The main idea described in PR conversation is to make retry logic.

Are you trying to interract with sandbox or production Apple server?

> I get errors for every request from second one

By the way, how many errors you got?

I'm asking because of for past 24 hours I got about 70,000 failes because of 
cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

And 25,000 errors because of iTunes 503-error.

So, yes, that happens. And just you can do it is make a retry.

**Comment by zahidurr** [comment]
> The main idea described in PR conversation is to make retry logic.
> 
> Are you trying to interract with sandbox or production Apple server?

production

> 
> > I get errors for every request from second one
> 
> By the way, how many errors you got?

Around 500

> 
> I'm asking because of for past 24 hours I got about 70,000 failes because of
> cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> 
> And 25,000 errors because of iTunes 503-error.
> 
> And it is less than 1% of all requests.
> 
> So, yes, that happens. And just you can do it is make a retry.

I tired make a retry but it’s still same issue.
