### ISSUE TITLE
"code": 403, Android

### ISSUE THREAD

**Issue by zigou13** [aporat/store-receipt-validator#120]
Hello, I have a problem with Android with service account here is the error below

```
{
  "error": {
    "code": 403,
    "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
    "errors": [
      {
        "message": "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console.",
        "domain": "androidpublisher",
        "reason": "projectNotLinked"
      }
    ]
  }
}

```

Do you have an idea of my problem?
Thank You

**Comment by stefanobianchini** [comment]
@zigou13 take a look to this article: https://stackoverflow.com/questions/50208046/service-account-doesnt-show-up-in-google-play-console-after-creation

You have to create the service account with a role (it's not optional). Which role? I've tested Product Owner

**Comment by Stafox** [comment]
@zigou13 hi. I have misssed this issue. Looks like configuration problem. Did you solve it?

**Comment by Stafox** [comment]
This happens when you project are not linked with service account. In that case you should just link it in google console.

Sometimes, when issue still exist need to add/remove in-app product.
Sometimes, upload a new APK may help.

In other cases need to contact Google Support.
