### ISSUE TITLE
base64 data for apple receipt

### ISSUE THREAD

**Issue by sgaykhe** [aporat/store-receipt-validator#124]
Hi,
Can someone guide me how to get the base64 data from apple? i have the numberic transaction key i received from apple.

**Comment by aporat** [comment]
You need to get the receipt data from the device itself. see https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store.

I'm not aware of a method to retrieve the receipt data from the transaction id. I recommend asking on stackoverflow as it's not an issue with the library
