### ISSUE TITLE
Reduce dependencies size

### ISSUE THREAD

**Issue by Orkin** [aporat/store-receipt-validator#128]
Hello @aporat,

I have a suggestion to reduce the size of google dependencies. The google package has at least 200 services and for the receipt purpose we don't need all of thoses. What do you think about adding in composer.json an extra command to reduce the package size or just add documentation about that. It's explain here in google sdk documentation : https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services

With this the google sdk switch from 58M to 928K 😉 

I notice we only need AndroidPublisher service what do you think about this enhancement ?

**Comment by Stafox** [comment]
I agree with that. But it should be done on the final project where this lib is going to be implemented.

**Comment by Orkin** [comment]
Yes that the scope of my PR #129 ;)
