### ISSUE TITLE
usage guide without composer

### ISSUE THREAD

**Issue by nevonevo** [aporat/store-receipt-validator#131]
Hi there and thanks for this codes. Is there anyway to use this without composer because i have shared hosting and i can not use composer. If i can please write a guide how i can use without composer. I read another information from you and you said if you don't use composer you have to include libraries and files manually. But i really don't know which files i will include and where to include. thanks and best regards.

**Comment by Stafox** [comment]
Hi.

This lib wasn’t configured to use without composer from the box. But you can do it easily using autoload.

https://www.php.net/manual/en/language.oop5.autoload.php
