### ISSUE TITLE
Play Store Receipt return ununderstandable object

### ISSUE THREAD

**Issue by YudeMgoy** [aporat/store-receipt-validator#132]
Why the response return data like this? what is this? 
![Capture](https://user-images.githubusercontent.com/45964922/96357117-6cb00500-1121-11eb-886c-f5824f88b242.PNG)

this is my code on server side
` require_once app_path().'/../vendor/autoload.php';
        
        // receipt data
        $packageName = "com.smeatech.weeby";
        $productId = "weeby_premium2";
        $purchaseToken = "olgkmglhgekmamomdhfaeidm.AO-J1OzIeJpD-lu1wJbbneIRXY_2Plzp6scVRfcAHtrxyW1tCQFVumpASKR0Pgk5c9TDqKLVgRxtC_75ziaPvyVDndYbIzUx7w";
        
        $client = new \Google_Client();
        $client->setApplicationName("Weeby");
        $client->setAuthConfig(app_path().'/googleserviceconfig.json');
        $client->setScopes([\Google_Service_AndroidPublisher::ANDROIDPUBLISHER]);
        
        $validator = new PlayValidator(new \Google_Service_AndroidPublisher($client));
        
        try {
            $response = $validator->setPackageName($packageName)->setProductId($productId)->setPurchaseToken($purchaseToken)->validateSubscription();
            
            return response()->json($response);
        } catch (Exception $e) {
            echo 'got error = '.$e->getMessage().PHP_EOL;
        }`

**Comment by Stafox** [comment]
Could you show the raw response? you shown response handled by your response() function.

**Comment by YudeMgoy** [comment]
![Capture](https://user-images.githubusercontent.com/45964922/96576197-07fcd200-12fc-11eb-9406-63fcc7e4a43c.PNG)

Now it's return error like that

**Comment by Stafox** [comment]
Problem connected with other libraries, firebase-jwt in your case.
