### ISSUE TITLE
permissions issues

### ISSUE THREAD

**Issue by Gameonn** [aporat/store-receipt-validator#133]
I am getting this error
{ "error": { "code": 401, "message": "The current user has insufficient permissions to perform the requested operation.", "errors": [ { "message": "The current user has insufficient permissions to perform the requested operation.", "domain": "androidpublisher", "reason": "permissionDenied" } ] } }

**Comment by Stafox** [comment]
Absolutely clear error provided by api. Your service account should have permission to read financial information.

**Comment by Gameonn** [comment]
But the account with which I have created service account and all other stuff has permissions to read financial data.

**Comment by Stafox** [comment]
![image](https://user-images.githubusercontent.com/1101646/96808174-fe20bf00-1420-11eb-92d8-d29f39a5b4b6.png)

**Comment by Gameonn** [comment]
Yes exactly the same permissions I have. Has this problem anything to do with in-app products? 

My in-app products were already created and now I am setting up store validation API. But I have updated my in-app products and then regenerated the service account json keyfile.

Btw, here my code if anything is wrong over here:
```
        $googleClient = new \Google_Client();
        $scope = ['https://www.googleapis.com/auth/androidpublisher'];
        // $googleClient->setScopes([\Google_Service_AndroidPublisher::ANDROIDPUBLISHER]);
        $googleClient->setApplicationName('bulletforce');
        $googleClient->setScopes($scope);
        $pathToServiceAccountJsonFile = json_decode(Storage::disk('local')->get('keys/test.json'), true);
        $googleClient->setAuthConfig($pathToServiceAccountJsonFile);

        $validator = new PlayValidator(new \Google_Service_AndroidPublisher($googleClient));

        try {
          $response = $validator->setPackageName('com.blayzegames.iosfps')
              ->setProductId(PRODUCT_ID)
              ->setPurchaseToken(TEST_PURCHASE_TOKEN)
              ->validatePurchase();
        } catch (\Exception $e){
            echo $e->getMessage().PHP_EOL;
        }
```

Thanks

**Comment by Stafox** [comment]
It can take up to 36 hours for your Play Service Credentials to work properly with the Android Developer API.

Also make sure that service account connected with the app.

**Comment by Gameonn** [comment]
Yes the service account is linked with the app. 

I was expecting it to work as soon as I generated the json key, but let's wait for 36 hours in order to check whether it works or not.

Thanks @Stafox

**Comment by Gameonn** [comment]
@Stafox 
Still I am facing the same permissions error: 
`{ "error": { "code": 401, "message": "The current user has insufficient permissions to perform the requested operation.", "errors": [ { "message": "The current user has insufficient permissions to perform the requested operation.", "domain": "androidpublisher", "reason": "permissionDenied" } ] } }`

Please help me fix this.

Thanks

**Comment by Stafox** [comment]
Sorry, but I have no idea how to help.
Time-to-time we got issues like yours connected with permissions.
I just can recommend try to configure service account from scratch following these steps: https://docs.revenuecat.com/docs/creating-play-service-credentials

**Comment by Gameonn** [comment]
Thanks for the steps, i'll try this once more. 

Besides your suggestion, I tried this as well https://stackoverflow.com/a/60691844/4198180, but it didn't work.

I shared my code last time, can you please review it once and see if there is something wrong in it?

Thanks

**Comment by Stafox** [comment]
The code looks fine.

**Comment by Gameonn** [comment]
@Stafox I was able to fix the permissions issue. But the bigger problem still prevails.

![image](https://user-images.githubusercontent.com/6601996/97395431-ed81b480-190a-11eb-9bd6-6b6ba0965148.png)

Here's what I get in response. But this response doesn't provides any information about the transaction like whether it was a valid transaction or not and other details.

Thanks

**Comment by Stafox** [comment]
It shouldn’t. I mean that correct response (without errors) from google api tells that transaction is valid. But to decide provide to user premium functionality or not you should by your own.

Regards

**Comment by johnkhansrc** [comment]
@Gameonn 
> I was able to fix the permissions issue.

How did you solve the problem ?
Is it just a matter of time ?  _(36 hours)_
