### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by lagox** [aporat/store-receipt-validator#134]
Hi! I have moved to new vps server and redeployed my project. But ItunesValidator have some problems, when I validate receipt. On the local machine your library work fine, but in production I see this error:

> {
  "message": "Client error: `POST https://buy.itunes.apple.com/verifyReceipt` resulted in a `400 Bad Request` response:\n<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 400 Bad Request</title>\n< (truncated...)\n",
  "exception": "GuzzleHttp\\Exception\\ClientException",
  "file": "/home/developer/sites/getmonetika/www/releases/1/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php",
  "line": 113,

**Comment by Stafox** [comment]
Sounds like the issue can be connected with your production data. Make sure you pass into validate method receipt base 64.

**Comment by lagox** [comment]
> Sounds like the issue can be connected with your production data. Make sure you pass into validate method receipt base 64.
> […](#)
> 26 окт. 2020 г., в 20:00, Lagox ***@***.***> написал(а): Hi! I have moved to new vps server and redeployed my project. But ItunesValidator have some problems, when I validate receipt. On the local machine your library work fine, but in production I see this error: { "message": "Client error: POST [https://buy.itunes.apple.com/verifyReceipt`](https://buy.itunes.apple.com/verifyReceipt%60) resulted in a 400 Bad Request response:\n\n\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<title>Error 400 Bad Request</title>\n< (truncated...)\n", "exception": "GuzzleHttp\Exception\ClientException", "file": "/home/developer/sites/getmonetika/www/releases/1/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php", "line": 113,` — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, I send base64 receipt.

**Comment by lagox** [comment]
In server I don't have a php-curl library, when I'm install this library - all work. Close issue
