### ISSUE TITLE
Not getting any info to check valid transaction

### ISSUE THREAD

**Issue by Gameonn** [aporat/store-receipt-validator#135]
![image](https://user-images.githubusercontent.com/6601996/97786739-a2e68d80-1bd3-11eb-8582-4b687a4eae41.png)

Here's what I get in response. But this response doesn't provides any information about the transaction like whether it was a valid transaction or not and other details.

Thanks

**Comment by Stafox** [comment]
It shouldn’t. I mean that correct response (without errors) from google api tells that transaction is valid. But to decide provide to user premium functionality or not you should by your own.
