### ISSUE TITLE
Huawei AppGallery support

### ISSUE THREAD

**Issue by amal** [aporat/store-receipt-validator#137]
Would be awesome if this library also supports Huawei AppGallery.

[Documentation](https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/iap-order-service-purchase-token-verification-v4)
[Server-side project sample](https://communityfile-drcn.op.hicloud.com/FileServer/getFile/cmtyManage/011/111/111/0000000000011111111.20200529105220.92628749179158194036972080012617:50510821035028:2800:0B278289EEF2E48EB054FCE909516D89AC2A6D78B4D20425A9DC891D386FB06F.zip?needInitFileName=true) (multilang, including PHP), [source](https://developer.huawei.com/consumer/en/doc/development/HMS-Examples/iap-example-v4)

**Comment by Stafox** [comment]
I already have an implementation of AppGallery, but maybe will publish it as a separate lib,

**Comment by Stafox** [comment]
@amal you can find implementation here: https://github.com/Stafox/huawei-iap
