### ISSUE TITLE
How to determine valid receipts in google play?

### ISSUE THREAD

**Issue by Gameonn** [aporat/store-receipt-validator#143]
In iTunes, we have methods like `isValid()` and `getReceipt()`, do we have similar methods in google play as well?? 

What are the methods to determine whether it is a test/sandbox purchase or real purchase??

**Comment by Stafox** [comment]
If you got a response from google api with status 200 - purchase is valid.

What kind of service provide to customer depends on your logic.

To detect sandbox purchase use method getPurchaseType().

More info here: https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptions

**Comment by Gameonn** [comment]
Presently I am using `getPurchaseType()` method but in real purchase I get `null` value and for sandbox I get `0` value. 
Rest response remains same for sandbox and production.

**Comment by Stafox** [comment]
> Presently I am using `getPurchaseType()` method but in real purchase I get `null` value and for sandbox I get `0` value.
> Rest response remains same for sandbox and production.
> 
> Is this the expected behaviour?

Yes, it is also described in documentation. `purchaseType=0` is about sandbox.
_The type of purchase of the subscription. This field is only set if this purchase was not made using the standard in-app billing flow. Possible values are: 
0. Test (i.e. purchased from a license testing account) 
1. Promo (i.e. purchased using a promo code)_

> Are there any other methods for the above response that I can execute in order to check sandbox purchase?
no.
