### ISSUE TITLE
From where I can get the application name for Google Play Validation?

### ISSUE THREAD

**Issue by kariae** [aporat/store-receipt-validator#145]
Hello, 

Thanks for the awesome package, working like a charm for iTunes, I'm trying to configure Google Play validation, I created the service account and linked it to the Google Play Console, but still, I receive `"The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."` I suspect the application name from here `$googleClient->setApplicationName('...');` since I don't know what to put in there?

Thanks

**Comment by Stafox** [comment]
As I remember it does not matter what specified in application name.

Try google about you issue. Created service account should be linked to the app.

**Comment by kariae** [comment]
I can confirm this, for my issue I had to create a new product, thanks
