### ISSUE TITLE
Google cloud email 

### ISSUE THREAD

**Issue by blood73** [aporat/store-receipt-validator#163]
I received this email: 

"Hello Google Cloud Storage Customer,

We are writing to let you know that the authentication workflow used by stand-alone installation of Cloud Storage CLI gsutil is being deprecated on January 31, 2023. We have determined that you have used user account authentication for standalone installation of gsutil for accessing Cloud Storage in the last 30 days."

Do I need any actions with this library? What I can change?

**Comment by Stafox** [comment]
Nothing connected to this library.
