### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by marijap93** [aporat/store-receipt-validator#166]
Hi, would it be possible to get a new release, please? I'd like to use the recently added function of getting the `ExternalAccountId`.
Thank you

**Comment by Stafox** [comment]
Hello.

You still able to get the externalAccountId and other fileds using raw response (can be obtained by [AbstractResponse::getRawResponse()](https://github.com/aporat/store-receipt-validator/blob/master/src/GooglePlay/AbstractResponse.php#L70)).

```
$externalAccountId = $subscriptionResponse->getRawResponse()->getExternalAccountId();
```
