### ISSUE TITLE
Apple 'verifyReceipt' endpoint is deprecated, This method is currently used to verify receipt

### ISSUE THREAD

**Issue by ajithnow** [aporat/store-receipt-validator#175]
As per Apple Developer Documentation, the _'verifyReceipt'_ is deprecated. Source : [Apple Developer Documentation](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt)

The same method is being used in the package to obtain receipt details:

https://github.com/aporat/store-receipt-validator/blob/0791b760dc4b9473d80782b85954eff15372212c/src/iTunes/Validator.php#L275

/aporat/store-receipt-validator/src/iTunes/Validator.php :: sendRequestUsingClient

Line Number: 275

**Comment by Stafox** [comment]
Duplicates #174
