### ISSUE TITLE
Upcoming changes to the App Store Receipt Signing Intermediate Certificate

### ISSUE THREAD

**Issue by Paco777** [aporat/store-receipt-validator#182]
Hello,
I have just noticed this new post from Apple about some Upcoming changes to the App Store Receipt Signing Intermediate Certificate.

Here is the link: [https://developer.apple.com/news/?id=b6tejt6f](https://developer.apple.com/news/?id=b6tejt6f)

I believe store-receipt-validator is not impacted, but could you please give a confirmation.
I'm still using version 4.4, in case it matters.

Thank you.

**Comment by Stafox** [comment]
Hello, as described in the article it might affect the validation process that happens on device. I do not expect that it somehow will affect sever-to-server receipt validation. However, I want to highlight that this way of receipt validation leveraged by this library marked as [deprecated](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/validating_receipts_with_the_app_store), and it can stop to work anytime (hope Apple will notify and provide enough time to migrate to alternative way).

**Comment by Paco777** [comment]
OK, thank you.
