### ISSUE TITLE
Removed setIStoreSharedSecret function (backward incompatibility)

### ISSUE THREAD

**Issue by chekalskiy** [aporat/store-receipt-validator#23]
According to semver 1.3.0 should be 2.0 because of changing public method setIStoreSharedSecret().

I am using it in that way and I think somebody may too.
```php
$validator->setSharedSecret('12345');
$response = $validator->setReceiptData($data)->validate();
```

**Comment by aporat** [comment]
thanks. I'll keep that in mind in future releases. if you feel it's critical, feel free to open a pull request with the restored function and i'll create a new tag for that release
