### ISSUE TITLE
Update "google/apiclient" require

### ISSUE THREAD

**Issue by NikColt** [aporat/store-receipt-validator#3]
Hello! Could you update "google/apiclient" require to "1.1.*@dev" in your composer.json?

**Comment by aporat** [comment]
Thanks. I'll take a look on that issue again. 

The latest google php client uses the new v2 google play publisher api which rely on a different authentication method. I didn't spend enough time to figure out how to use it yet.

**Comment by aporat** [comment]
closed by #7
