### ISSUE TITLE
Error when composer update

### ISSUE THREAD

**Issue by elvack** [aporat/store-receipt-validator#36]
Hi, this is a nice package and I've been using this package since long time ago but recently I try to update composer and appears an errors like this :

composer update
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove phpseclib/phpseclib 0.3.10
    - Conclusion: remove laravel/framework v4.2.22
    - Conclusion: don't install laravel/framework v4.2.22
    - Conclusion: don't install laravel/framework v4.2.21
    - Conclusion: don't install laravel/framework v4.2.20
    - Conclusion: don't install laravel/framework v4.2.19
    - Conclusion: don't install laravel/framework v4.2.18
    - Conclusion: don't install laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.16
    - Conclusion: don't install laravel/framework v4.2.15
    - Conclusion: don't install laravel/framework v4.2.14
    - Conclusion: don't install laravel/framework v4.2.13
    - Conclusion: don't install laravel/framework v4.2.12
    - Conclusion: don't install laravel/framework v4.2.11
    - Conclusion: don't install laravel/framework v4.2.10
    - Conclusion: don't install laravel/framework v4.2.9
    - Conclusion: don't install laravel/framework v4.2.8
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install laravel/framework v4.2.6
    - Conclusion: don't install laravel/framework v4.2.5
    - Conclusion: don't install laravel/framework v4.2.4
    - Conclusion: don't install laravel/framework v4.2.3
    - Conclusion: don't install laravel/framework v4.2.2
    - Conclusion: don't install laravel/framework v4.2.1
    - Conclusion: don't install phpseclib/phpseclib 0.3.10
    - Installation request for laravel/framework ~4.2 -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.18, v4.2.19, v4.2.2, v4.2.20, v4.2.21, v4.2.22, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - Conclusion: don't install phpseclib/phpseclib 2.0.4
    - Conclusion: don't install phpseclib/phpseclib 0.3.1|install phpseclib/phpseclib 2.0.4
    - Conclusion: don't install phpseclib/phpseclib 0.3.5|install phpseclib/phpseclib 2.0.4
    - Conclusion: don't install phpseclib/phpseclib 0.3.6|install phpseclib/phpseclib 2.0.4
    - Conclusion: don't install phpseclib/phpseclib 0.3.7|install phpseclib/phpseclib 2.0.4
    - Installation request for aporat/store-receipt-validator dev-master -> satisfiable by aporat/store-receipt-validator[dev-master].
    - Conclusion: don't install phpseclib/phpseclib 0.3.8|install phpseclib/phpseclib 2.0.4
    - aporat/store-receipt-validator dev-master requires google/apiclient ~2.0 -> satisfiable by google/apiclient[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.1.0].
    - google/apiclient v2.0.0 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - google/apiclient v2.0.1 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - google/apiclient v2.0.2 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - google/apiclient v2.0.3 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - google/apiclient v2.1.0 requires phpseclib/phpseclib ~2.0 -> satisfiable by phpseclib/phpseclib[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - Can only install one of: phpseclib/phpseclib[2.0.0, 0.3.0].
    - Can only install one of: phpseclib/phpseclib[2.0.1, 0.3.0].
    - Can only install one of: phpseclib/phpseclib[2.0.2, 0.3.0].
    - Can only install one of: phpseclib/phpseclib[2.0.3, 0.3.0].
    - laravel/framework v4.2.0 requires phpseclib/phpseclib 0.3.* -> satisfiable by phpseclib/phpseclib[0.3.10, 0.3.0, 0.3.1, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9].
    - Conclusion: don't install phpseclib/phpseclib 0.3.9|install phpseclib/phpseclib 2.0.4

Sorry, I don't know which part is wrong. Thanks.

**Comment by aporat** [comment]
Looks like laravel 4 uses an older version of one of the dependencies. you'll either have to install v1.4 of this library or upgrade to laravel 5

**Comment by elvack** [comment]
Thanks for your quick response. So true I'm using laravel 4 because it's long project. So what should I do to install library become v1.4 ?

**Comment by aporat** [comment]
in your composer.json, set the desired version, such as:

```
"require": {
    "aporat/store-receipt-validator": "1.4.*"
},
```

**Comment by elvack** [comment]
Ok I will try to change it. Thanks.
