### ISSUE TITLE
do i have to use DNS to active ?

### ISSUE THREAD

**Issue by Imohamed** [aporat/store-receipt-validator#38]
dear do i have to use wifi with DNS or i can just MAP the domain to the script ?

**Comment by aporat** [comment]
not sure what you mean. this is a php server-side library, which communicates with apple and google web services via HTTPS.

**Comment by Imohamed** [comment]
how to install and use in iphone ?

**Comment by aporat** [comment]
https://www.amazon.com/iOS-Development-Dummies-Jesse-Feiler/dp/1118871057

**Comment by Imohamed** [comment]
ohh nice but i think you did not write how to setup loool
