### ISSUE TITLE
Class 'ReceiptValidator\GooglePlay\ServiceAccountValidator' not found

### ISSUE THREAD

**Issue by thangytp** [aporat/store-receipt-validator#40]
Can you tell me how to fix it?

**Comment by DFoxinator** [comment]
I noticed this too. I'm guessing maybe the author accidentally forgot to commit the class, because it's definitely not in the codebase.

If it's not too much trouble, I would say just use the oath method, that one works perfectly it seems.

**Comment by felipefrancisco** [comment]
@aporat I believe you forgot to add this class to the project? :P

**Comment by Stafox** [comment]
Guys, for now you don't need ServiceAccountValidator class.

Just use the following code.

```
        $googleClient = new \Google_Client();
        $googleClient->setScopes([\Google_Service_AndroidPublisher::ANDROIDPUBLISHER]);
        $googleClient->setApplicationName('Your_Purchase_Validator_Name');
        $googleClient->setAuthConfig($pathToServiceAccountJsonFile);

        $googleAndroidPublisher = new \Google_Service_AndroidPublisher($googleClient);
        $validator = new \ReceiptValidator\GooglePlay\Validator($googleAndroidPublisher);
```
