### ISSUE TITLE
Use it without Composer

### ISSUE THREAD

**Issue by Abichai** [aporat/store-receipt-validator#42]
Hi I'm trying to use the store-receipt-validator without using Composer since I can't use it right now. So I would like to know how can I use this script without composer ?

**Comment by dragonfire1119** [comment]
@Abichai You would need to manually download the repo & extract the src validators to your directory then ``require_once('src/{Your validator}')``. 

Composer just autoloads the files for you so if you don't use composer you need to load the files yourself.
