### ISSUE TITLE
Where to add the sharedSecret

### ISSUE THREAD

**Issue by ef33zy** [aporat/store-receipt-validator#50]
Hi,

Pardon my ignorance/limited knowledge, where do I add/include the sharedSecret value obtained from iTunesConnect?
I do not want to include it in the app (which I assume is bad practice anyway)

Would I need to change in the Validator.php:

 ` protected $_sharedSecret = null;`
to:
 ` protected $_sharedSecret = 'myOwnSharedSecret';`?

Thanks for your help.

**Comment by albertleao** [comment]
Hello! Just ran into this issue as well. Reading through the code I found the following method

`public function setSharedSecret($secret)`

You can run this function on your instantiated validator and it will work.

**Comment by ef33zy** [comment]
Hi @albertleao, when you say '...run this function on your instantiated validator...' how do you mean?

**Comment by albertleao** [comment]
`$validator->setSharedSecret($secret);`

**Comment by ef33zy** [comment]
Hi @albertleao Thanks for that, it works as below, with the receipt data 'hard-coded' in there (`$receiptBase64Data`), just need to figure how to without hard-coding it in.
Thanks once again.

![image](https://cloud.githubusercontent.com/assets/15075449/25593662/8f69a648-2eb5-11e7-8bf7-387cffcfff6d.png)

**Comment by albertleao** [comment]
Environment variables, config files... there are several ways to do that but it's outside the scope of this library.
