### ISSUE TITLE
Amazon RVSSandbox Verification Issue

### ISSUE THREAD

**Issue by aderae** [aporat/store-receipt-validator#52]
In Amazon -> Validator:

Localhost RVSSandbox verification url is not valid. It is defined as follows:

const ENDPOINT_SANDBOX = 'http://localhost:8080/RVSSandbox/';

However it has to be:

const ENDPOINT_SANDBOX = 'http://localhost:8080/RVSSandbox/version/1.0/verifyReceiptId/';

And we cannot override endpoint because of the protected value and exception handling in the constructor.

**Comment by aporat** [comment]
closed by #69
