### ISSUE TITLE
Git Ignore on the entire folder

### ISSUE THREAD

**Issue by lucamicheli** [aporat/store-receipt-validator#55]
I've Installed the library on my project with composer. 
After that, I cannot figure out how to include on git. 
It cannot see the entire folder aporat inside the vendor folder. 
I've no .gitignore at all. 

Any thought about this?

**Comment by aporat** [comment]
not sure I understand. if you install the library with composer, make sure `vendor` folder is included in the ignored files of `.gitignore`
