### ISSUE TITLE
Missing iTunes Receipt fields from Response class

### ISSUE THREAD

**Issue by ktzouno** [aporat/store-receipt-validator#56]
Greetings,

while reading the iTunes documentation I noticed a few non-existing (probably new) fields from ReceiptValidator\iTunes\Response as described in https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

- latest_expired_receipt_info
- pending_renewal_info
- is-retryable

Would be nice to include them as well :)

**Comment by nielsmouthaan** [comment]
I added at least the pending renewal info as part of this PR: https://github.com/aporat/store-receipt-validator/pull/59

**Comment by Hirbod** [comment]
Possible you could also add the other two fields? @nielsmouthaan ?
@aporat would be lovely if would still support your awesome class..
