### ISSUE TITLE
iOS 7+ receipts validation

### ISSUE THREAD

**Issue by Juanmaramon** [aporat/store-receipt-validator#57]
Apple deprecated transaction receipt base64 data way back in iOS 7. That means iOS 11 will fully remove it so you need to switch your code over to use the "new" app receipt.

Is it possible to validate a receipt (iOS 7+) using the "new" base64 encoded receipt with this validator?

**Comment by aporat** [comment]
do you have more information about that change? as far as I know, JSON encoded base64 receipt is the only possibility.

https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

**Comment by renekliment** [comment]
This library can do both transaction receipts and the _new_ app receipts.

You have to be careful though. In `->getLatestReceiptInfo()`, you get an array and if you want the latest transaction receipt, you have to select the latest (what I do is sort by expiration date in ms and get the last).
