### ISSUE TITLE
Apple receipt validation. Add exclude-old-transactions

### ISSUE THREAD

**Issue by alitvinenko** [aporat/store-receipt-validator#64]
Hi!
Can you have added apple receipt validation option "exclude-old-transactions"?

Description of this option located this: https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW3

**Comment by aporat** [comment]
closed by #65
