### ISSUE TITLE
Google Play Response Error ( Cannot Encode to JSON )

### ISSUE THREAD

**Issue by omkarjadhav** [aporat/store-receipt-validator#68]
Hey,
We are trying to use this wrapper. It works great for iTunes but for Google Play Store we are getting an issue in response. After var_dump($response) we get this ->

`ReceiptValidator\GooglePlay\PurchaseResponse Object ( [response:protected] => Google_Service_AndroidPublisher_ProductPurchase Object ( [consumptionState] => 1 [developerPayload] => com.myCompany.myAppName [kind] => androidpublisher#productPurchase [orderId] => GPA.XXXX-XXXX-XXXX-XXXX [purchaseState] => 0 [purchaseTimeMillis] => 1234567890123 [purchaseType] => 0 [internal_gapi_mappings:protected] => Array ( ) [modelData:protected] => Array ( ) [processed:protected] => Array ( ) ) [developerPayload:protected] => )
`
we are not able to encode it to JSON format .

( Masked my app ID and order ID on purpose )

**Comment by gsingh1** [comment]
@omkarjadhav - You can get the raw response using `getRawResponse()` method `PurchaseResponse ` on and then encode to json!.

**Comment by roshimon** [comment]
@gsingh1 getRawResponse() does the trick. Thanks :+1:
