### ISSUE TITLE
Fatal error: Class 'ReceiptValidator\GooglePlay\Validator' not found

### ISSUE THREAD

**Issue by romaniom** [aporat/store-receipt-validator#72]
Здравствуйте! Я видел, что такой вопрос уже был и что он закрыт, но я не понял как решить эту проблему? Я первый раз вижу композер и вообще далёк от пхп.
Я пробовал валидатор.пхп ложить  в каталог

**Comment by Stafox** [comment]
Начните с изучения Composer. Это не проблема библиотеки
https://getcomposer.org/doc/00-intro.md
https://getcomposer.org/doc/01-basic-usage.md

Try to learn composer at first. It's not a library issue.

Should be closed.
