### ISSUE TITLE
iTunes Code 21006 is Treated as Invalid

### ISSUE THREAD

**Issue by kalebdf** [aporat/store-receipt-validator#73]
In the iTunes `Response` the receipt code `21006 - RESULT_RECEIPT_VALID_BUT_SUB_EXPIRED` should be treated as **VALID** since it is a valid receipt but the subscription has expired. Today, it is treated as an **INVALID** code.

https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

**Comment by gsingh1** [comment]
It has always been treated as invalid in general cases. If you see the Parse the Response section in the above link, it clearly states:

> Either 0 if the receipt is valid, or one of the error codes listed in Table 2-1.

>For iOS 6 style transaction receipts, the status code reflects the status of the specific transaction’s receipt.

>For iOS 7 style app receipts, the status code is reflects the status of the app receipt as a whole. For example, if you send a valid app receipt that contains an expired subscription, the response is 0 because the receipt as a whole is valid.

You can always override the default `isValid()` behaviour in `Response` or use a different check that caters to your business logic understanding of what a **VALID** and **INVALID** receipt is.

**Comment by kalebdf** [comment]
@gsingh1 Okay. Sounds good! 👍We were using the `isValid()` to determine if it was parseable and a legit receipt. In our use case, we are processing the receipt from the webhook and handling the canceled/expired case.

**Comment by gsingh1** [comment]
I'm doing something very similar.

See example below of how I work out both if its a valid receipt and is expired:

```
public function validateLatestRenewal($receiptBase64Data)
    {
        $response = $this->ITunesValidator->validate($receiptBase64Data);

        if (!$response->isValid()) {
            throw new CoreException(ErrorCodes::IAP_ITUNES__INVALID_RECEIPT, __('messages.iap_itunes__invalid_receipt'));
        }

        $latestReceipt = collect($response->getLatestReceiptInfo())->last(function ($subscriptionReceipt) {
            return $subscriptionReceipt->getExpiresDate() !== null
                && $subscriptionReceipt->getExpiresDate()->gt(Carbon::now());
        });

        if (is_null($latestReceipt)) {
            throw new CoreException(ErrorCodes::IAP_ITUNES__SUB_EXPIRED, __('messages.iap_itunes__sub_expired'));
        }

        return $latestReceipt->getRawResponse();
    }
```

Hope that helps.
