### ISSUE TITLE
[Android] validatePurchase() results in 401 Login Required

### ISSUE THREAD

**Issue by agrove91** [aporat/store-receipt-validator#74]
I feel like I followed the Readme for Android validation but I am getting an error on validatePurchase()

    $client = new \Google_Client();
    $client->setApplicationName('AppName');
    $client->setAuthConfig('/path/to/client_credentials.json');
    $client->setScopes('https://www.googleapis.com/auth/androidpublisher');

    $validator = new PlayValidator(new \Google_Service_AndroidPublisher($client));

    $bundle = \Config::get('app.bundle_id');
    $productId = $bundle.'.amount_'.$amount;

    try {
      $response = $validator->setPackageName($bundle)
        ->setProductId($productId)
        ->setPurchaseToken($receipt->purchaseToken)
        ->validatePurchase();

    } catch (Exception $e){
      \Log::error($e->getMessage()); <--------------------------- output
      $api->errors()->add('errors',$e->getMessage());
      return $api;
    }

output

    {
      "error": {
        "errors": [
          {
             "domain": "global",
             "reason": "required",
             "message": "Login Required",
             "locationType": "header",
             "location": "Authorization"
          }
       ],
       "code": 401,
       "message": "Login Required"
       }
    }

**Comment by gsingh1** [comment]
`$client->setAuthConfig('/path/to/client_credentials.json');`

Ensure the contents of this JSON file are correct and you have a valid service account with correct permission and authority setup.

See more on how to set this up on Google documentation - https://developers.google.com/api-client-library/python/guide/aaa_client_secrets

**Comment by agrove91** [comment]
Thanks gsingh1! while digging into that link I found the solution. 

The following is in case anyone runs into the same problem. 

I had to add the below code.

    $client->setAccessToken($access_token);

Then I got this error

    "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."

So I also had to double check that my google developer and google play developer were linked as well.

[Stackoverflow](https://stackoverflow.com/questions/25481207/why-getting-error-the-project-id-used-to-call-the-google-play-developer-api-has
)

Its a google complexity issue but as this was my first time using more in-depth google tools, it just meant more digging.

**Comment by hiren004** [comment]
@agrove91  Can you please let me know what token i need to put here?
I'm getting error like Login required.
My code is like:

                    

> $client = new \Google_Client();
> $client->setApplicationName('APP_NAME');
> $client->setAuthConfig(public_path('credentials.json'));
> $client->setScopes('https://www.googleapis.com/auth/androidpublisher');
>                     
> $validator = new PlayValidator(new \Google_Service_AndroidPublisher($client));
> $response = $validator->setPackageName($findSubscription->title)
>                                             ->setProductId($request->product_id)
>                                             ->setPurchaseToken($request->purchase_token)
>                                             ->validatePurchase();
>                     dd($response);

Please help me!!
