### ISSUE TITLE
Not working for google play when validate a receipt

### ISSUE THREAD

**Issue by hiren004** [aporat/store-receipt-validator#81]
I'm using this package for google play and iTunes. iTunes seems working great for me, but when i was trying to implement it for google play it's giving me some error. I don't know how to use this for google play OR how to fix it!

Please help me with this one. I'm using this code by the way:

```
$client = new \Google_Client();
$client->setApplicationName('APP_NAME');
$client->setAuthConfig(public_path('credentials.json'));
$client->setScopes('https://www.googleapis.com/auth/androidpublisher'); 
$validator = new PlayValidator(new \Google_Service_AndroidPublisher($client));

try {
      $response = $validator->setPackageName('PACKAGE_NAME')
                            ->setProductId($request->product_id)
                            ->setPurchaseToken($request->purchase_token)
                            ->validatePurchase();
       var_dump($response);
 } catch (Exception $e){
         return response()->json([
                 'errorCode'  => '1',
                 'errorMsg'   => 'Receipt is not valid',
                 'data'       => []
         ]);
}
```

Any help will be really appreciated!! 
Thanks!

**Comment by rms5981** [comment]
What is your response outputting? Check to see that you are able to communicate with the Google API server. Also, as mentioned in the README there is some footwork that needs to be done with your google play store and using a service account prior to using the code ( if that's the route you took to authenticate).

**Comment by hiren004** [comment]
@rms5981 I've fixed it now and it's working for me now. 
Thank you!

**Comment by rms5981** [comment]
@hiren004 Awesome!
