### ISSUE TITLE
Following semver and codestyle

### ISSUE THREAD

**Issue by Stafox** [aporat/store-receipt-validator#86]
What about if we strongly will follow semver (https://semver.org/) and PSR-2 codestyle (https://www.php-fig.org/psr/psr-2/)?

At least let's start to use variables and properties in camelCase and increasing major version if backward compatibility was breaked.

@aporat I'm ok if you will mention me when merge is needed to check possible BC violations.

**Comment by soren121** [comment]
Yes, _please_ follow semver. The upgrade to 2.2.0 broke my application, which shouldn't ever happen on a minor version upgrade.

**Comment by aporat** [comment]
thanks, @Stafox you're right. I'll tag a new major release when there are breaking changes in the api from now on
