### ISSUE TITLE
Latest release is 5.7.4 on Packagist

### ISSUE THREAD

**Issue by loic-couharde** [aporat/store-receipt-validator#88]
Hi,

Latest release on [Packagist](https://packagist.org/packages/aporat/store-receipt-validator) is 5.7.4 but it is 3.0.0 on Github, is it normal knowing the 5.7.4 is nonfunctional ?

Thx

**Comment by Stafox** [comment]
The diff shows only one file change .editorconf.
It might be a bug on github side. Let's wait a comment from @aporat

**Comment by aporat** [comment]
yeah, pretty strange. all the release tags from https://github.com/aporat/laravel-console-mutex somehow got pushed into this repository. thanks for letting me know. i'll clean up those release tag.

**Comment by loic-couharde** [comment]
Thx @aporat for the version cleaning ;)
