### ISSUE TITLE
Not working for google play when validate a receipt

### ISSUE THREAD

**Issue by safciplak** [aporat/store-receipt-validator#91]
string(172) "{ "error": { "errors": [ { "domain": "global", "reason": "invalid", "message": "Invalid Value" } ], "code": 400, "message": "Invalid Value" } } "

my response is that. Please help me.

**Comment by Stafox** [comment]
It means you had sent incorrect data. Check bundle id, purchase token and product id.

**Comment by safciplak** [comment]
Thank you so much for your turn back. I used android test information data. This is test product and my app is Closed channel or track.

"productId": "android.test.purchased"
"packageName":"mypackagename"
"purchaseToken":"inapp:mypackagename:android.test.purchased"

what should I do?

**Comment by safciplak** [comment]
i don't know what i need for test products. i'm stuck. i need help i after that hope this is useful issue.

**Comment by Stafox** [comment]
At first looks like you sent request to validate inapp , but handle it as subscription.


Share a code, maybe I’ll able to help

**Comment by safciplak** [comment]
Here you are
https://paste.ubuntu.com/p/qS4npwWNBc/

**Comment by Stafox** [comment]
So, clear now. You generated the token (test one).
I didn't find in google documentation how the purchase token should be. (https://developer.android.com/google/play/billing/billing_testing)
By the way, it looks like not possible to use these product IDs on server side to test validation. So, these product ids might be used on client side only.

**Comment by safciplak** [comment]
Maybe i can create a test account on google after that i can try again real purchase one with test account.

**Comment by Stafox** [comment]
Yeap. You will. Follow this https://developer.android.com/google/play/billing/billing_testing#prepare

**Comment by safciplak** [comment]
The code is correct. My fault is i used android test informations like start inapp start with and android.test.purchased product is wrong response. 

If you can create test account on https://play.google.com/apps/publish in app products after that everything is working.

Thank you so much @Stafox for helping. 

The issue can be closed.
