### ISSUE TITLE
Documentation unclear where to find credentials for Google Play

### ISSUE THREAD

**Issue by brandonsavage** [aporat/store-receipt-validator#92]
For someone new to this project who has never before validated a receipt, Apple seems to make it easy while Google seems to make it hard. There's room for clarity in the documentation on how to find the credentials you need to make a valid request to Google.

**Comment by djaygit** [comment]
+1

**Comment by lesha888** [comment]
+1

**Comment by JamesPoel** [comment]
++++++1

**Comment by Stafox** [comment]
You need a service account. Try to follow these links: https://support.google.com/cloud/search?q=service+account&from_promoted_search=true

**Comment by Stafox** [comment]
@brandonsavage @djaygit You can join the telegram group to ask questions about android subscription flow:
http://t.me/iap_android

**Comment by Stafox** [comment]
The latest described and working way how to create the Service account described here: https://docs.revenuecat.com/docs/creating-play-service-credentials
