### ISSUE TITLE
getPurchases vs getLatestReceiptInfo

### ISSUE THREAD

**Issue by jonlod** [aporat/store-receipt-validator#97]
More of a question. We noticed with the iTunes validator that the flow described uses **getPurchases** to check the data. Our apps send the latest receipt to the server on daily basis but we noticed some user subscriptions ending prematurely. 
I started testing out for one specific user and found that using **getPurchases** on the saved receipt, gave us 3 purchases but that user had already paid for 4. When I use **getLatestReceiptInfo**, I get 4 purchases, including the missing one. 
Question now: what is the difference? Is it safe to use getLatestReceiptInfo or can this include non-paid/failed purchases? 
Thanks

**Comment by Stafox** [comment]
Method `getPurchases()` returns data which contains in receipt. `getLatestReceiptInfo()` returns transactions which contains in the latestReceipt.

So, if you get value from `latestReceipt` and valdate it you will get 4 transactions in `getPurchases()` too.
There are no failed transactions in receipt info.

**Comment by Stafox** [comment]
Please, read the doc for details: https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

**Comment by jonlod** [comment]
I have been reading what documentation I could find but still, info is pretty vague for iTunes compared to other payment services. 
Weird that the app keeps sending an older receipt to the server for some users because they keep getting missing purchases (getPurchases) with the receipt they send to the server.. I'll keep running both checks just in case but good to know it's safe to use. 
Thanks

**Comment by Stafox** [comment]
I guess app should call some refresh() method to fetch latest receipt from Apple server.
